stages:
    - code_quality
    - test
    - deploy

test_unit:
    image: gandronic/blog_php
    before_script:
    - composer install
    script: bin/phpunit

hadolint
    image: hadolint/hadolint
    script: 
    - hadolint Dockerfile

